// UNA CLASE ES UNA PLANTILLA DE UN ELEMENTO DE LA VIDA REAL  
// PUEDE SER RAZA HUMANA,  AUTOMOVIL , ENEMIGO , ANIMAL   

//UN OBJETO ES UNA INSTANCIA DE ESA CLASE Y ES MÁS ESPECIFICA POR EJEMPLO: 
// LA CLASE AUTOMOVIL PUEDE SER COCHE , MOTO , AVIÓN .  

//CONCEPTO DE HERENCIA ES CUANDO CREAMOS OTRA CLASE APARTE PERO QUEREMOS REUTILIZAR 
// LOS MÉTODOS Y PROPIEDADES DE OTRA QUE NOS PUEDAN SERVIR  

